### ISSUE TITLE
Why binary is 56mb when fr31/spotifylyrics is 18mb sir

### ISSUE THREAD

**Issue by erkantaylan** [SimonIT/spotifylyrics#12]
Thank you continuing the repo. I appriciate your effort.

**Comment by SimonIT** [comment]
Thank you. If you want to support me, I got a new patreon account.

Indeed, it's a good question why mine is five time larger. I actually have no clue. This is the command how I build the exe:
https://github.com/SimonIT/spotifylyrics/blob/11ba36bcd316d89b322d98f2e332fd3e86e983ce/.travis.yml#L34
Maybe @fr31 uses some args to compress it more.

**Comment by fr31** [comment]
@SimonIT 

I used this spec file for pyinstaller.

[spotifylyrics.txt](https://github.com/SimonIT/spotifylyrics/files/4160377/spotifylyrics.txt) (spotifylyrics.spec)

and then I ran:
>pyinstaller.exe spotifylyrics.spec

**Comment by SimonIT** [comment]
Thank you! And nice to hear something from you :D I will try it for the next release

**Comment by SimonIT** [comment]
That's the generated one I used:

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['SpotifyLyrics.pyw'],
             pathex=['D:\\Software\\Entwicklung\\spotifylyrics'],
             binaries=[],
             datas=[('icon.png', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='SpotifyLyrics',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False , icon='icon.ico')
```
I don't see any significant differences

**Comment by Arecsu** [comment]
Mmmm, I might take a look if I have time. The binary size is much bigger and at least in my computer it opens after 20 secs, while my old build and the latest from fr31 opens in 2 sec max.

Btw, great work! Updated my fork to add a primitive cache function and turns out there's one already. Love it!

**Comment by SimonIT** [comment]
Confusing, I looked into the  generated [xref-SpotifyLyrics.html.txt](https://github.com/SimonIT/spotifylyrics/files/4165917/xref-SpotifyLyrics.html.txt) by pyinstaller and there are modules mentioned which are not imported by the project, like for example
```
pyi_rth_django.py Script
imports: django.core.management • django.utils.autoreload • sys
imported by: SpotifyLyrics.pyw
```
Maybe this is the reason for the big size? But I don't know why django gets packaged

**Comment by Arecsu** [comment]
I suspect there are new libraries that depends on other ones and so one, creating a bloated big executable. What I found out is that by executing the last release by cloning the repo, no pyinstaller binary, is that it opens fast enough.

When I debug the latest binary from pyinstaller, a big chunk of time is spent just decompressing the files to finally launch the app. 

A workaround would be making a setup file, skiping the decompress process every time it opens. Is pyinstaller capable of doing that?

**Comment by SimonIT** [comment]
I absolutely don't know. I only used pyinstaller for this project to release. I read on in their docs that we can disable the upx compression, but I think that will result in a bigger exe, which could be faster.

I originally tried to automate the deploy process with travis to have only included the dependencies it needs. Maybe this could be an option to make it smaller. I will look at it again because last time it didn't work at all

**Comment by SimonIT** [comment]
I just tried generating the exe with the spec file by fr31. The resulting exe has the same size as mine

**Comment by SimonIT** [comment]
After several hours of hitting my head against the wall I can say that the deploying on windows via travis. works. The file has a size of around 37 MB, which is a lot smaller than my previous exe's, but nevertheless bigger than fr31 ones.

**Comment by Arecsu** [comment]
Great! As long as it opens fast it's totally fine :)

**Comment by SimonIT** [comment]
I just released 1.5
Feel free to try it. In my opinion it's faster than before

**Comment by Arecsu** [comment]
Nice!! I've made a quick comparison with the last build from fr31

fr31 Spotify 1.21 64 bits — 4.79 sec
SimonIT Spotify 1.5 64 bits — 4 sec

It even improved startup times. Would be great someday to reach less than 1 sec but I don't think it would be posible in a single binary bundled with a python interpreter on it. But who knows.

Thanks for your work, I love every single new feature :)

**Comment by SimonIT** [comment]
I think everyone is happy, so I close this
