### ISSUE TITLE
Better song tittle parsing

### ISSUE THREAD

**Issue by Arecsu** [SimonIT/spotifylyrics#20]
Hi! There are certain songs that can't be searched properly because special characters in their names.

Just to name one I'm having a problem right now: "Green Day - Holiday / Boulevard of Broken Dreams".

Every lyric provider, including Genius, return the lyrics of "Holiday". Due to Spotify having the version where both songs are combined into 1 track, it would have to search for a lyric that has both songs. 

Genius has the lyrics here: https://genius.com/Green-day-holiday-boulevard-of-broken-dreams-lyrics. So, I think the problem lies within the artist - title parsing part of the code. I can't point more songs having this issue but I remember having experienced something like this before.

Thanks a lot for your work!

**Comment by SimonIT** [comment]
So what do you suggest? Removing these lines?
https://github.com/SimonIT/spotifylyrics/blob/376a4d1fbd15bd0bffb1d1423891a7ba686a6a3b/backend.py#L54-L55
I don't know if this has side effects on other songs. I'm not use if some has slashes in their names for some other information

**Comment by Arecsu** [comment]
I can't think of situations where the forward slash would break something. But it was there in the first place for some reason. Let's test it with the next release and see the results.
