### ISSUE TITLE
Windows download

### ISSUE THREAD

**Issue by Tylo-m** [SimonIT/spotifylyrics#25]
Hello :)

The readme says that if i wanna install for windows i should download the .exe file. Sadly there is no exe file, i assume the readme might be out of date, so how should one go on installing spotifylyrics on windows ?

Thanks ! :)

**Comment by SimonIT** [comment]
![image](https://user-images.githubusercontent.com/11720038/85453621-5ee7da00-b59c-11ea-9df3-16f4a42a7dc1.png)

Where are you searching the exe? Because for me every release has an exe in its assets

**Comment by Tylo-m** [comment]
Oh yes sry, i missed it with that new github interface. Thank you !
