### ISSUE TITLE
Please let the user choose the lyrics directory

### ISSUE THREAD

**Issue by PeterCodar** [SimonIT/spotifylyrics#28]
This is a great tool, thanks for it @SimonIT 

Could you please add some functionality to choose a custom lyrics path?
Actually, I have saved tens of thousands of *.txt files on my D: data drive.

So the path should be `D:\Data\Lyrics\S\Supertramp (Logical Song).txt`
(instead of the fixed path `C:\Users\%username%\AppData\Roaming\SpotifyLyrics\lyrics`)

A commandline option like /LyricsPath would already be a great start .-)

**Comment by SimonIT** [comment]
You can put something like this inside your settings.ini:

```
[settings]
syncedlyrics = True
alwaysontop = False
openspotify = False
darktheme = True
info = True
minimizetotray = False
fontsize = 15
streamingservice = Spotify
fullscreen = False
maximized = True
x = 2559
y = 415
width = 1280
height = 1001
LyricsPath = D:\\
```
