### ISSUE TITLE
/bin/bash: xwininfo: command not found

### ISSUE THREAD

**Issue by kamalhm** [SimonIT/spotifylyrics#3]
Building directly from my linux maching (Manjaro KDE), when I run the .pyw the terminal outputs this, 

```bash
/bin/bash: xwininfo: command not found
```
The program itself seems to be working fine, just want to let you know

**Comment by SimonIT** [comment]
That's interesting. I tested it on Kali Linux and it doesn't appear.  I think it's not a problem if the program works

**Comment by SimonIT** [comment]
I found out the causing problem. You don't have the command `xwininfo` on your machine installed and spotifylyrics tries to get the song with this command
