### ISSUE TITLE
The newest.exe doesn't work. The debug version doesn't work but in a different way.

### ISSUE THREAD

**Issue by crimson-king** [SimonIT/spotifylyrics#30]
Hey. 
I'm using Windows 10.
I am simply unable to download the newest version (1.54) via github (tried on Firefox and Chrome). It does download but then it says that the download failed and running .exe (which seems to have downloaded) just gives me an error that I can't run it on this system.
I tried bypassing it - and downloaded it on my phone, then transferred it on my PC. But after transferring it, after clicking on the .exe it just says I can't open it (worded a bit differently than the previous error) and then it just disappears from the hard drive. The other difference is that the SpotifyLyrics downloaded by the phone had an icon while the 'failed downloads' did not.

I downloaded debug version (1.52) and it runs. But it doesn't download any lyrics. Even on popular songs like Deep Purple - Perfect Strangers, which definitely have the lyrics included. The console debug says simply "Musixmatch: list index out of range" or "Songmeanings: list index out of range". Then again, it could be because it's an outdated version but as you know I can't run the normal one.

Any hints?

P.S. Also yeah, taking songs from Genius would be nice - I feel it has a bigger base than Musicxmatch.

**Comment by DarylGraves** [comment]
Just tested this on my machine:

- When downloading the file, it downloads but Edge (Chromium) immediately warns that it may not be safe. I had to click the dots and select "Keep Anyway"
- After this, when I ran the .exe it comes up with a warning that Microsoft Smartscreen has blocked it. If you click "More info" you can choose "run anyway" and it will load.

I'm not sure if that's the same issue you're having? Without knowing the exact error message I could be going down the wrong route.

**Comment by SimonIT** [comment]
Sadly there's not much I can do about it see #22. If you know a way how can I do it without spending money, please let me know

**Comment by SimonIT** [comment]
#21 is the problem with the not opening window. It would be nice if you can post a screenshot of the problem there
