### ISSUE TITLE
the font is weird when I use it 

### ISSUE THREAD

**Issue by Louissenny** [SimonIT/spotifylyrics#32]
Hey @SimonIT , shout out to your wonderful work! 
The app works perfectly, the only problem is somehow the font it used is different (and ugly) in my end, maybe it's due to my Windows version? I am using the Windows 10 Home China version.
![image](https://user-images.githubusercontent.com/32843517/100772591-c3a43c00-343a-11eb-9571-c4d39d4c9d77.png)
Is there any why I can modify the font used in the app? Such as altering the _settings.ini_ ? 
Thanks again for your work!

**Comment by SimonIT** [comment]
Just recognized that changing the font is already supported.
Could you try to set your favorite font like in this commit f9c4b5a in your _theme.ini_?

**Comment by SimonIT** [comment]
Closing because of no response whether it's solved or not
