### ISSUE TITLE
(Suggestion) Text alignment options

### ISSUE THREAD

**Issue by ChrisEickelman** [SimonIT/spotifylyrics#37]
Would love to have the option to center-align and right-align text in addition to the default.
Thanks for making this!

**Comment by SimonIT** [comment]
Have you looked at the [example-theme.ini](https://github.com/SimonIT/spotifylyrics/blob/master/example-theme.ini)? `LyricsTextAlign` is already supported (It may not have worked in 1.54 because I made a mistake in variable naming. But it's fixed in 1.55)

**Comment by ChrisEickelman** [comment]
That is beautiful, thank you!
