### ISSUE TITLE
Terminates when saving while no lyrics present

### ISSUE THREAD

**Issue by barsnick** [SimonIT/spotifylyrics#4]
Thanks for the new version 1.30.

When I press the "Save lyrics" button right after launch, when no lyrics are displayed (yet), the programs simply terminates.

(When lyrics are displayed, all is well, although I needed to check the source on Github to figure out where they're stored. ;-))

I assume ```def save_lyrics(self):``` needs to exit earlier on non-existence of lyrics.

**Comment by SimonIT** [comment]
On windows is a button under settings for opening the lyrics directory  ;-)
