### ISSUE TITLE
Synced Lyrics Suggestion

### ISSUE THREAD

**Issue by bellyrose** [SimonIT/spotifylyrics#48]
It'd be nice to have the option for the current line to just have a highlighted background instead of it being larger and bold. Maybe an option in the theme.ini to change the color of the highlight as well.

**Comment by SimonIT** [comment]
Sorry for the long delay, I had university stuff to do.
You can now just set `CurrentLineBackgroundColor` for the background color and change the ratio with `currentLineSizeRatio`. If the  size shouldn't change, set 1.0
