### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by N1NJ4** [SimonIT/spotifylyrics#54]
Hey, would love this to work for Spotify Stations..

**Comment by SimonIT** [comment]
Isn't Spotify Stations an Android / iOS app?

**Comment by N1NJ4** [comment]
unsure which it is, though there is a webapp, and the two slightly different versions for android and iOS, unsure which copy's, or is the basis.

Though obviously, I'm asking for spotifylyrics to regard the webapp of Stations; Which I believe there are multiple versions of Spotify itself, application, online, webapp?. so unsure just how different the details are.

**Comment by N1NJ4** [comment]
Stations doesn't exist any longer. no need to care. thank you though!
