### ISSUE TITLE
is this malw ? 

### ISSUE THREAD

**Issue by DRWOLF03** [SimonIT/spotifylyrics#68]
W64/CookieStealer.G.gen!Eldorado 

MD5
8e59db866ec05bbd4c177de075b8076c 
SHA-1
5228ed9e80d60cfc6a5118de775eef44264d86e3 
SHA-256
5d62b564e39c0f748847ce00d04e34bad1471cccc115886d4a8773e7485cd432

**Comment by SimonIT** [comment]
Take a look at #42
